# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: soylog_development
  pool: 
  host: localhost
  # username: adamwong
  # password: devpass

test:
  adapter: postgresql
  encoding: unicode
  database: soylog_test
  pool: 5
  username: adamwong
  password: devpass

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
